# Generated by Django 5.1.5 on 2025-03-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
